### PR TITLE
Update logout

### PR DESCRIPTION
**Pull request by n0mn0m**
- Use a logout endpoint instead of routing to a confirmation page

ref: https://github.com/helxplatform/development/issues/707
pending: https://github.com/helxplatform/appstore/pull/109/files

### CODE REVIEW

**Comment by n0mn0m** [comment]
@connectbo the associated appstore PR has merged and you can test this out locally with `make build.npm compose.appstore`.

**Review by connectbo — COMMENTED** [review]
Sorry for miss the notification. But thanks for these! I am refactoring some of our code as Matt and I talked about the code architecture a little bit we thought we should let other developers( students) easily jump in and poke around. That includes separate those axios calls and make them standalone in context provider. I can help adding this logout call into that as well, does that sounds like a plan?

**Comment by n0mn0m** [comment]
@connectbo will that be done this week/early next? Not sure the scope of the changes.

**Comment by connectbo** [comment]
Will be done by this week. Most of those are happening on the app page, lots of changes :)

**Comment by n0mn0m** [comment]
Sounds good to me. I'll close this thanks.

**Pull request closed without merging**
