### PR TITLE
Studies histogram gh

### PR DESCRIPTION
**Pull request by gingin77**
Hi @mbwatson I updated the name of the function called by the pushpin to `toggleVariablesByStudy` and handled variable bar selection accordingly.

Also, I muted the color. Aquamarine felt a little too extra.

There's still an issue where bars selected by study get lost when a user zooms in, but I think we are probably in an ok place to meet with Hannah now.

### CODE REVIEW

**Comment by gingin77** [comment]
@mbwatson - oh great and thanks! I have a meeting with Hannah and Kira tomorrow morning that will likely lead to some tweaks and possibly new bugs revealed.

**Comment by frostyfan109** [comment]
@gingin77 This is really awesome. Excited to see this added in the near future.

FYI I will handle the merging into develop since #186 made some major changes to how layout is handled.

Notes:
- I'm guessing the icon is just a placeholder, though I would suggest `AreaChartOutlined` or `BarChartOutlined`.
- There should be a bit more of a margin (thinking 16px) between the vertically-spaced components to stay consistent with other parts of the site.
- It may be nice to have the pinned studies appear at the top of the list so that you can easily tell what is pinned/unpin them.
- The results header is a little wordy now, the extra study info may be more appropriate in another container elsewhere, not really sure.
- The button container may make more sense below the graph. Then the "variables according to dug" text could be made into a header i.e. using `Typography.Title`. Something like this:
image


Bugs I found:
- There is some strange hanging occurring when a search is executed. Memoizing `ConceptsList` helped, but there seems to be more to it than just that.
- There needs to be some sort of enforced zoom limit. If you keep zooming past the single-variable level (because of course some people like me will 🙂) it can crash the page.

**Comment by frostyfan109** [comment]
@gingin77

Thanks for taking a look at my review.

Just to be clear, I haven't really reviewed any of the code. I looked around a bit but nothing critical. I'd be happy to do an actual code review in the future before the merge to develop if that would be helpful.

One thing I'm noticing this time around is that `variable-results.js` is bit of a behemoth. I'm not sure how much of this can actually be separated out, though ideally the entire layout would not be encapsulated within a single file/hook.
- At the most basic level, I'd separate the histogram and variable/study lists into two standalone components.

> I'm guessing the icon is just a placeholder, though I would suggest AreaChartOutlined or BarChartOutlined.

I was referring the ellipsis icon used in the grid selection component:

image

> There should be a bit more of a margin (thinking 16px) between the vertically-spaced components to stay consistent with other parts of the site.

Vertical spacing could be added via hard-coded margins or `Space`. For reference:
- `<Space size="small">` corresponds to a 8px margin, and this is the default when `size` isn't given.
- `<Space size="middle">` is 16px.
- `<Space size="large">` is 24px.

You could also use `24px` margins if you think it looks better. I just wouldn't use anything less than `16px`. Regardless, I think using `<Space>` is probably best here. There are a number of places in the code that don't use Space, and instead use hard-coded margins or replicate the behavior of Space, but this is just because there are drawbacks to how Space works that mean it sometimes can't be used well.

> I'm remembering that there is some file clean-up/reorganizing that we should do.

The project is definitely in need of some cleanup in general. This hasn't been addressed as far as I know; Matt hasn't been working much on the UI, and I haven't gotten around to it either.

> The results header is a little wordy now, the extra study info may be more appropriate in another container elsewhere, not really sure.

I didn't really explain my thought process much here. I think the info is useful to have, it's just that when you look at the header now, there are 4 different metrics a user has to take in from a single "sentence" (concept count, study count, variable count, page count), and it's just a bit too much for me. And to make it even worse, #191 changed the header to (x of y pages) so there'd be __5__ things now.

> There is some strange hanging occurring when a search is executed. Memoizing ConceptsList helped, but there seems to be more to it than just that.

I think I said this because beforehand React was memoizing `ConceptsList`. You changed some stuff around in `results.js` and it isn't anymore. So whenever any of the *many* pieces of state change that `SearchResults` uses from the search context, it induces a re-render of `ConceptsList`.

I personally haven't ran into performance problems with the studies layout, but breaking it down into more components would probably help improve performance to some extent.

**Comment by gingin77** [comment]
- [ ] Summary sentence - 4 different metrics a user has to take in from a single "sentence" (concept count, study count, variable count, page count)
- [ ] Vertical spacing 
- [ ] Separate the histogram and variable/study lists into two standalone components
- [ ] Bring back "View Last Zoom"
- [ ] Start conversation with Hannah, Kira, Alex regarding the icon for the Toggle - Concepts vs Variables - should we use Histogram Icon?

**Comment by gingin77** [comment]
I think there's something wrong related to how I'm using `setVariableStudyResults` vs `setVariableResults` - will return to this next chance I can keep debugging/making fixes

**Comment by gingin77** [comment]
Re commit [b66ad29](https://github.com/helxplatform/helx-ui/pull/183/commits/b66ad29ce0a09db4951e9d593c74d252735f9343), use `Title` instead of `Text`

**Comment by frostyfan109** [comment]
@gingin77 These are some ui features I'd like to see after messing around with the view some more:

- [ ] Title/header improvements (beyond just "Variables according to DUG score".
  - I think an addition like `Zoomed into variables with scores in 90-94th percentile` or something along those lines may be a good approach to help the user keep track of where in the overall histogram they are zoomed into.
- [ ] Pinned studies should appear at the top of the list
  - Sorry, this ended up getting lost somewhere down the line, and we didn't end up discussing this. I think intuitively, a user expects a pinned UI component to appear at the top of a list, but this isn't the current behavior. E.g. in the screenshot below, I have the study "NIDA-CTO0010" pinned, but it doesn't appear at the top of the list.
image


- [ ] Margins need to be cleaned up on the studies list
  - Specifically the left borders next to each variable under a study clash with the overall border of the study container, so these need to be properly spaced out.
  - There's also too much space between the study name/pushpin header and the variables list container.
image

- [ ] The left border next to each variable under a study is very difficult to see due to the gray background.
  - Either it needs to be darker, or you could remove it and do something like I've done with the CDEs UI instead (see screenshot). The left handle turns blue when hovered, and collapses the interface when you click on it.
image


- [ ] There should be some sort of interface from left clicking a variable in the histogram or studies list. Otherwise, the interactivity of the interface will be pretty limited overall. It may be worthwhile to have a discussion with some more people about what this interface would do and what it would look like.
  - One idea I have is that it opens an interface to select concepts associated with the variable/study, and then maybe you can select a concept and view it, though maybe this isn't the direction we want to go in for the variables layout.
  - Maybe it suggests other searches/concepts associated with the variable/study that you can redirect the search to.
  - Etc.

**Pull request merged**
