### PR TITLE
Merge develop to master v 3.0

### PR DESCRIPTION
**Pull request by waTeim**
Take all that is in develop and merge to master, count on ccv to tag it v3.0.0

### CODE REVIEW

**Comment by Hoid** [comment]
Two things: you'll need to update the branch with the latest master, and also I don't see a commit here with "BREAKING CHANGE: " at the start (or anywhere in it). this is required for the tag to go to v3.0.0

**Review by Hoid — CHANGES_REQUESTED** [review]
See comments above

**Comment by waTeim** [comment]
So I did a bare push earlier today, and I answered "breaking" to the multiple choice questions.  I can do so again?

Commits on Feb 16, 2023
[Release commit](https://github.com/helxplatform/helx-ui/pull/237/commits/6c69e77f4899522ce22d7a94604711e5dbe7236a)

@[waTeim](https://github.com/helxplatform/helx-ui/commits?author=waTeim)
waTeim committed 9 hours ago
 
[feat: helx ui 3](https://github.com/helxplatform/helx-ui/pull/237/commits/e6cd0a51d786dc24bbab711d794169e878ad5487)

@[waTeim](https://github.com/helxplatform/helx-ui/commits?author=waTeim)
waTeim committed 9 hours ago

**Comment by Hoid** [comment]
let's take a look at the official rules for CCV to make sure that the commit script is working. this will be the first time we've used it for a breaking change since I tested it back when we made it, so we should definitely make sure the commit is in the right format.

**Review by Hoid — APPROVED** [review]

**Review by joshua-seals — APPROVED** [review]
Looks good to me.

**Pull request merged**
